name: vizard
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - pandas
  - numpy
  - matplotlib
  - plotly
  - seaborn
  - IPython
  - beautifulsoup4
  - pip
  - pip:
      - mkdocs
      - mkdocs-material
      - mkdocstrings
      - highlightjs-pygments
      - mkdocs-search
      - mkdocs-git-revision-date-plugin