site_name: Vizard Documentation
site_description: Documentation for the Vizard library
site_author: Data Team Force

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_source: true
            docstring_style: google
          

nav:
  - Home: index.md
  - Reference:
      circular_graph:
        Overview: circular_graph_index.md
        Modular_graph: modular_graph.md
        Color_tools: color_tools.md
        Tools: tools.md
  - How to contribute ?: contribution.md
  - Demo: demo.md

